"""create basic models

Revision ID: 04ce0e98d80e
Revises: 
Create Date: 2025-11-29 01:35:59.055199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ce0e98d80e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'DONE', 'ERROR', name='uploadstatus'), nullable=False),
    sa.Column('has_validation', sa.Boolean(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('texts',
    sa.Column('text_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'DONE', 'ERROR', name='textstatus'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('predicted_label', sa.String(), nullable=True),
    sa.Column('src', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.upload_id'], ),
    sa.PrimaryKeyConstraint('text_id')
    )
    op.create_table('validations',
    sa.Column('validation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.text_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_table('texts')
    op.drop_table('uploads')
    # ### end Alembic commands ###
