FROM python:3.9-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml .

COPY model_service/onnx_model_package/ .

COPY model_service/onnx_inference.py .

RUN uv sync

EXPOSE 8000

CMD ["uv", "run", "python", "model_service/onnx_inference.py"]


